{{- if and .Values.transacoes.canary.enabled .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-api-transacoes-canary
  namespace: tipsbank-transacoes
  labels:
    {{- include "tipsbank.labels" . | nindent 4 }}
    app: api-transacoes
    version: v2
  annotations:
    {{- if .Values.ingress.tls.enabled }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.tls.issuer }}
    {{- end }}
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: {{ .Values.transacoes.canary.weight | quote }}
    nginx.ingress.kubernetes.io/canary-by-header: {{ .Values.transacoes.canary.headerName | quote }}
    nginx.ingress.kubernetes.io/canary-by-header-value: {{ .Values.transacoes.canary.headerValue | quote }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.apiHost }}
      secretName: tipsbank-api-tls
  {{- end }}
  rules:
    - host: {{ .Values.ingress.apiHost }}
      http:
        paths:
          - path: /transacoes(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: api-transacoes-v2
                port:
                  number: 8080
{{- end }}
