apiVersion: v1
kind: Service
metadata:
  name: postgres-headless
  namespace: tipsbank-contas
  labels:
    {{- include "tipsbank.labels" . | nindent 4 }}
    app: postgres
spec:
  clusterIP: None
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
