apiVersion: v1
kind: Secret
metadata:
  name: secret-db
  namespace: tipsbank-contas
  labels:
    {{- include "tipsbank.labels" . | nindent 4 }}
    app: api-contas
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  POSTGRES_DB: {{ .Values.postgres.db | quote }}
  DB_URL: {{ printf "postgresql+psycopg://%s:%s@postgres-headless.tipsbank-contas.svc.cluster.local:5432/%s" .Values.postgres.user .Values.postgres.password .Values.postgres.db | quote }}
