apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-auditoria-nfs
  namespace: tipsbank-auditoria
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-ganesha
