# LoadBalancer — provisionamento automático de NLB via in-tree AWS cloud provider.
controller:
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"

  ingressClassResource:
    name: nginx
    enabled: true
    default: true

  admissionWebhooks:
    enabled: true

  config:
    proxy-body-size: "10m"
    proxy-read-timeout: "60"
    proxy-send-timeout: "60"
    allow-snippet-annotations: "true"
    limit-req-status-code: "429"
