apiVersion: v1
kind: Secret
metadata:
  name: secret-db
  namespace: tipsbank-transacoes
  labels:
    {{- include "tipsbank.labels" . | nindent 4 }}
    app: api-transacoes
type: Opaque
stringData:
  DB_URL: {{ printf "postgresql+psycopg://%s:%s@postgres-headless.tipsbank-contas.svc.cluster.local:5432/%s" .Values.postgres.user .Values.postgres.password .Values.postgres.db | quote }}
