---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: tipsbank-web
  labels:
    {{- include "tipsbank.labels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes: [Ingress, Egress]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns-egress
  namespace: tipsbank-web
  labels:
    {{- include "tipsbank.labels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes: [Egress]
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-controller
  namespace: tipsbank-web
  labels:
    {{- include "tipsbank.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: web
  policyTypes: [Ingress]
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress-nginx
    ports:
    - port: 8080
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-to-apis
  namespace: tipsbank-web
  labels:
    {{- include "tipsbank.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: web
  policyTypes: [Egress]
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: tipsbank-contas
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: tipsbank-transacoes
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: tipsbank-auditoria
    ports:
    - port: 8080
      protocol: TCP
