apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-app
  namespace: tipsbank-transacoes
data:
  CONTAS_URL: "http://api-contas.tipsbank-contas.svc.cluster.local:8080"
  AUDITORIA_URL: "http://auditoria.tipsbank-auditoria.svc.cluster.local:8080"
  APP_VERSION: "v1"
  LOG_LEVEL: "INFO"
  LOG_FILE: "/var/log/app/app.log"
