apiVersion: v1
kind: Secret
metadata:
  name: secret-db
  namespace: tipsbank-transacoes
type: Opaque
stringData:
  DB_URL: "postgresql+psycopg://tipsbank:tipsbank@postgres-headless.tipsbank-contas.svc.cluster.local:5432/tipsbank"
