# -*- mode: ruby -*-
# vi: set ft=ruby :

# Configuration variables
NodeCount = ENV['NODE_COUNT'] ? ENV['NODE_COUNT'].to_i : 2
ControlPlaneMemory = ENV['CP_MEMORY'] ? ENV['CP_MEMORY'].to_i : 4096
ControlPlaneCPUs = ENV['CP_CPUS'] ? ENV['CP_CPUS'].to_i : 4
NodeMemory = ENV['NODE_MEMORY'] ? ENV['NODE_MEMORY'].to_i : 4096
NodeCPUs = ENV['NODE_CPUS'] ? ENV['NODE_CPUS'].to_i : 2
EnableGUI = ENV['ENABLE_GUI'] == 'true' ? true : false
Provider = ENV['PROVIDER'] || "virtualbox"

Vagrant.configure(2) do |config|
  
  # Global VM settings
  config.vm.box = "bento/ubuntu-22.04"
  config.vm.box_version = "202510.26.0"
  config.vm.box_download_insecure = true
  config.vm.box_check_update = false
  
  # Global provisioning - requirements for all nodes
  config.vm.provision "shell", path: "scripts/requirements.sh", :args => NodeCount

  # Kubernetes controlplane
  config.vm.define "control-plane" do |controlplane|
    controlplane.vm.hostname = "controlplane"
    controlplane.vm.network "private_network", ip: "192.168.10.100"
    controlplane.vm.provider Provider do |v|
      v.memory = ControlPlaneMemory
      v.cpus = ControlPlaneCPUs
      v.gui = EnableGUI
      v.name = "k8s-control-plane"
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end
    controlplane.vm.provision "shell", path: "scripts/controlplane.sh"
    controlplane.vm.provision "shell", path: "scripts/post-install.sh", privileged: false
  end

  # Kubernetes worker nodes
  (1..NodeCount).each do |i|
    config.vm.define "node_#{i}" do |node|
      node.vm.hostname = "node#{i}"
      node.vm.network "private_network", ip: "192.168.10.#{i+1}"
      node.vm.provider Provider do |v|
        v.memory = NodeMemory
        v.cpus = NodeCPUs
        v.gui = EnableGUI
        v.name = "k8s-node-#{i}"
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      end
      node.vm.provision "shell", path: "scripts/node.sh"
    end
  end
end