{{- if .Values.monitoring.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-contas
  namespace: {{ .Values.monitoring.namespace }}
  labels:
    {{- include "tipsbank.labels" . | nindent 4 }}
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - tipsbank-contas
  selector:
    matchLabels:
      app: api-contas
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-transacoes
  namespace: {{ .Values.monitoring.namespace }}
  labels:
    {{- include "tipsbank.labels" . | nindent 4 }}
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - tipsbank-transacoes
  selector:
    matchLabels:
      app: api-transacoes
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: auditoria
  namespace: {{ .Values.monitoring.namespace }}
  labels:
    {{- include "tipsbank.labels" . | nindent 4 }}
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - tipsbank-auditoria
  selector:
    matchLabels:
      app: auditoria
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
{{- end }}
