# Backing store: local-path (rancher provisioner, default on kubeadm/vagrant)
persistence:
  enabled: true
  storageClass: local-path
  size: 10Gi

storageClass:
  name: nfs-ganesha
  reclaimPolicy: Retain
  archiveOnDelete: false
