apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-auditoria
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    # IP fixo do control-plane — definido no Vagrantfile (192.168.10.100)
    server: 192.168.10.100
    path: /srv/nfs/tipsbank-auditoria
