apiVersion: v1
kind: Secret
metadata:
  name: secret-db
  namespace: tipsbank-contas
type: Opaque
stringData:
  POSTGRES_USER: "tipsbank"
  POSTGRES_PASSWORD: "tipsbank"
  POSTGRES_DB: "tipsbank"
  DB_URL: "postgresql+psycopg://tipsbank:tipsbank@postgres-headless.tipsbank-contas.svc.cluster.local:5432/tipsbank"
