{{- if .Values.rbac.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-api-contas
  namespace: tipsbank-contas
  labels:
    {{- include "tipsbank.labels" . | nindent 4 }}
    app: api-contas
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-api-transacoes
  namespace: tipsbank-transacoes
  labels:
    {{- include "tipsbank.labels" . | nindent 4 }}
    app: api-transacoes
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-auditoria
  namespace: tipsbank-auditoria
  labels:
    {{- include "tipsbank.labels" . | nindent 4 }}
    app: auditoria
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-web
  namespace: tipsbank-web
  labels:
    {{- include "tipsbank.labels" . | nindent 4 }}
    app: web
---
# ServiceAccounts para os 4 perfis RBAC (token-based no EKS)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-operador-contas
  namespace: tipsbank-contas
  labels:
    {{- include "tipsbank.labels" . | nindent 4 }}
    app: rbac
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-operador-transacoes
  namespace: tipsbank-transacoes
  labels:
    {{- include "tipsbank.labels" . | nindent 4 }}
    app: rbac
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-auditor-global
  namespace: tipsbank-auditoria
  labels:
    {{- include "tipsbank.labels" . | nindent 4 }}
    app: rbac
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-sre
  namespace: tipsbank-contas
  labels:
    {{- include "tipsbank.labels" . | nindent 4 }}
    app: rbac
{{- end }}
