apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: tipsbank
  region: us-east-2
  version: "1.33"

iamIdentityMappings:
  - arn: arn:aws:iam::604179600406:user/lab-linuxtips
    username: eks-admin
    groups:
      - system:masters
    noDuplicateARNs: true

iam:
  withOIDC: true

managedNodeGroups:
  - name: workers
    desiredCapacity: 3
    instanceType: t3.medium

addons:
  - name: vpc-cni
    version: latest
    configurationValues: '{"enableNetworkPolicy": "true"}'
  - name: metrics-server
    version: latest
  - name: aws-ebs-csi-driver
    version: latest
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy
