---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: auditor-global-binding
  labels:
    app: rbac
    team: tipsbank
    env: prod
subjects:
  - kind: User
    name: auditor-global
    apiGroup: rbac.authorization.k8s.io
  - kind: ServiceAccount
    name: user-auditor-global
    namespace: tipsbank-auditoria
roleRef:
  kind: ClusterRole
  name: auditor-global
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sre-binding
  labels:
    app: rbac
    team: tipsbank
    env: prod
subjects:
  - kind: User
    name: sre
    apiGroup: rbac.authorization.k8s.io
  - kind: ServiceAccount
    name: user-sre
    namespace: tipsbank-contas
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
