---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: operador-contas-binding
  namespace: tipsbank-contas
  labels:
    app: rbac
    team: tipsbank
    env: prod
subjects:
  - kind: User
    name: operador-contas
    apiGroup: rbac.authorization.k8s.io
  - kind: ServiceAccount
    name: user-operador-contas
    namespace: tipsbank-contas
roleRef:
  kind: Role
  name: operador-contas
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: operador-transacoes-binding
  namespace: tipsbank-transacoes
  labels:
    app: rbac
    team: tipsbank
    env: prod
subjects:
  - kind: User
    name: operador-transacoes
    apiGroup: rbac.authorization.k8s.io
  - kind: ServiceAccount
    name: user-operador-transacoes
    namespace: tipsbank-transacoes
roleRef:
  kind: Role
  name: operador-transacoes
  apiGroup: rbac.authorization.k8s.io
