---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-api-contas
  namespace: tipsbank-contas
  labels:
    app: api-contas
    team: tipsbank
    env: prod
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-api-transacoes
  namespace: tipsbank-transacoes
  labels:
    app: api-transacoes
    team: tipsbank
    env: prod
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-auditoria
  namespace: tipsbank-auditoria
  labels:
    app: auditoria
    team: tipsbank
    env: prod
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-web
  namespace: tipsbank-web
  labels:
    app: web
    team: tipsbank
    env: prod
---
# ServiceAccounts para os 4 perfis RBAC (usados em kubeconfigs token-based no EKS)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-operador-contas
  namespace: tipsbank-contas
  labels:
    app: rbac
    team: tipsbank
    env: prod
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-operador-transacoes
  namespace: tipsbank-transacoes
  labels:
    app: rbac
    team: tipsbank
    env: prod
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-auditor-global
  namespace: tipsbank-auditoria
  labels:
    app: rbac
    team: tipsbank
    env: prod
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-sre
  namespace: tipsbank-contas
  labels:
    app: rbac
    team: tipsbank
    env: prod
