apiVersion: v1
kind: Service
metadata:
  name: auditoria
  namespace: tipsbank-auditoria
  labels:
    {{- include "tipsbank.labels" . | nindent 4 }}
    app: auditoria
spec:
  selector:
    app: auditoria
  ports:
    - name: http
      port: 8080
      targetPort: 8080
