apiVersion: apps/v1
kind: Deployment
metadata:
  name: auditoria
  namespace: tipsbank-auditoria
  labels:
    {{- include "tipsbank.labels" . | nindent 4 }}
    app: auditoria
spec:
  replicas: {{ .Values.auditoria.replicas }}
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: auditoria
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: auditoria
        team: {{ .Values.global.team }}
        env: {{ .Values.global.env }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: auditoria
                topologyKey: kubernetes.io/hostname
      securityContext:
        fsGroup: 65532
      containers:
        - name: auditoria
          image: {{ .Values.auditoria.image.repository }}:{{ .Values.auditoria.image.tag }}
          imagePullPolicy: {{ include "tipsbank.imagePullPolicy" . }}
          ports:
            - containerPort: 8080
          env:
            - name: DATA_DIR
              value: "/data"
            - name: LOG_LEVEL
              value: "INFO"
          resources:
            {{- toYaml .Values.auditoria.resources | nindent 12 }}
          startupProbe:
            httpGet:
              path: /health/startup
              port: 8080
            failureThreshold: 30
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            periodSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: auditdata
              mountPath: /data
      volumes:
        - name: auditdata
          persistentVolumeClaim:
            claimName: pvc-auditoria-nfs
