apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-auditoria-nfs
  namespace: tipsbank-auditoria
  labels:
    {{- include "tipsbank.labels" . | nindent 4 }}
    app: auditoria
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.auditoria.storageClass }}
  resources:
    requests:
      storage: {{ .Values.auditoria.storage }}
